# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- StableBuild

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: BatchScript@1
  inputs:
    filename: 'build.bat'
    arguments: 'pack'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.SourcesDirectory)/Build/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'internal'
    versioningScheme: 'off'